[package]
name = "app"
version = "0.1.6"
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "1.5", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.10"
sysinfo = "0.29"
walkdir = "2"
clap = { version = "4.4", features = ["derive"] }
zip = "0.6"
chrono = "0.4"
libc = "0.2"

[build-dependencies]
tauri-build = "1.5"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# it enables the custom protocol for the tauri:// scheme
custom-protocol = ["tauri/custom-protocol"]
